services:
  php-fpm:
    build:
      context: '.docker/php-fpm'
      target: os
    ports:
      - '${PHP_FPM_HOST_PORT:-9000}:9000'
    volumes:
      - ./:/var/www/indahash-crud/current
      - .docker/php-fpm/php.ini:/usr/local/etc/php/php.ini
    networks:
      - indahash-crud
    working_dir:
      /var/www/indahash-crud/current

  nginx:
    build:
      context: '.docker/nginx'
    ports:
      - '${NGINX_HOST_HTTP_PORT:-80}:80'
      - '${NGINX_HOST_HTTPS_PORT:-443}:443'
    volumes:
      - .docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - .docker/nginx/sites/:/etc/nginx/sites
      - .docker/nginx/ssl/:/etc/nginx/ssl
      - .docker/logs/nginx/:/var/log/nginx
      - ./:/var/www/indahash-crud/current
    networks:
      - indahash-crud
    depends_on:
      - php-fpm

  ###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    healthcheck:
      test: [ "CMD", "pg_isready", "-d", "${POSTGRES_DB:-app}", "-U", "${POSTGRES_USER:-app}" ]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - database_data:/var/lib/postgresql/data:rw
    networks:
      - indahash-crud
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

networks:
  indahash-crud:
    driver: bridge

volumes:
  ###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
