api_product_controllers:
    resource:
        path: ../src/Modules/Products/Presentation/Controllers
        namespace: App\Modules\Products\Presentation\Controllers
    type: attribute
    prefix: /api/products
    name_prefix: api_products_
